name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt install poppler-utils imagemagick
          pip3 install pdf2image
          npm install
          
      - name: Download images
        run: |
          ./get_images.py
          ls public/images
          
      - name: Build website
        run: |
          ./build_logo.sh
          npm run build
          zip -r build.zip build
          
      - name: Archive 
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: build.zip

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Archive 
        uses: actions/download-artifact@v2
        with:
          name: website
          
      - name: Extract archive
        run: |
          unzip build.zip

      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=build --functions=functions
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}          
