name: test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt install poppler-utils imagemagick
          pip3 install pdf2image
          npm install
      - name: Extract images
        run: |
          ./get_images.py
          ls public/images
      - name: Build website
        run: |
          ./build_logo.sh
          REACT_APP_GA_TRACKING_ID=${{ secrets.GA_TRACKING_ID }} npm run build
          zip -r build.zip build
